# -*- mode: sh -*-

if [[ $TERM != "screen" ]] exec screen -D -RR

# User configuration
typeset -U path cdpath fpath manpath

# autoload -U compinit; compinit
zstyle ':completion:*:sudo:*' command-path /usr/local/sbin /usr/local/bin \
                             /usr/sbin /usr/bin /sbin /bin /usr/X11R6/bin \
                             /usr/local/git/bin
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
fpath=(~/.zsh-completions $fpath)
autoload -Uz add-zsh-hock
autoload -Uz chpwd_recent_dirs cdr add-zsh-hook

test -f "$HOME/.envs" && source "$HOME/.envs"
test -f "$HOME/.alias" && source "$HOME/.alias"
test -f "$HOME/.funcs" && source "$HOME/.funcs"


export ZSH_LOCAL_DIR="$HOME/local/etc/zsh"

if [ ! -f "$ZSH_LOCAL_DIR/antigen.zsh" ]; then
    curl -L https://raw.githubusercontent.com/zsh-users/antigen/master/antigen.zsh > "$ZSH_LOCAL_DIR/antigen.zsh"
fi
source "$ZSH_LOCAL_DIR/antigen.zsh"

antigen bundle sorin-ionescu/prezto
if [ ! -L "$ZSH_LOCAL_DIR/antigen.zsh" ]; then
    ln -sfn ~/.antigen/repos/.zprezto ~/.zprezto
    ln -sfn ~/.zprezto/runcoms/zpreztorc ~/.zpreztorc
fi
antigen bundle mollifier/anyframe

source "$ZSH_LOCAL_DIR/anyframe.sh"
source "$ZSH_LOCAL_DIR/history.sh"
source "$ZSH_LOCAL_DIR/editor.sh"
source "$ZSH_LOCAL_DIR/program_plugin.sh"
source "$ZSH_LOCAL_DIR/emacs-term.sh"
source "$ZSH_LOCAL_DIR/yukitask.sh"

# PATHの重複除く
export PATH=`echo $PATH | perl -e 'my %path={}; my @list=(); foreach my $l (split(/:/, <STDIN>)){if(!exists($path{$l})){push(@list, $l);$path{$l}=1;}} print join(":", @list)'`




